* About

Simple set of files and utilities to make working through Peter Norvig's book
/Paradigms of Artificial Intelligence Programming: Case Studies in Common Lisp/
with GNU Emacs, SLIME and Make effortless - at least on the mundane tasks of
loading and bringing the right buffers up.

Usage is simple:

#+begin_src shell
make
#+end_src

This will first check if GNU Emacs daemon is already running,
and if not, start it. It will then check all the chapter
files to find how far the user has progressed in the book
and load the latest chapter file into Common Lisp.
It will then open SLIME's REPL buffer and the latest
chapter buffer from the end, so that user can start to
enter examples right away.

To load a specific chapter, command ~make chapNN~ can be used.
Here ~NN~ should be replaced with the chapter number
that is between 01-25, inclusive.
Note that numbers less than ~10~ have a leading zero.

* License

The MIT License:

#+begin_src
Copyright (c) 2021 octaspire.com

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
#+end_src
